In [50]:
%pip install tensorflow


[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [51]:
%pip install pandas


[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [52]:
%pip install scikit-learn


[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


# Import the libreries

In [73]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [54]:
tf.__version__

'2.16.2'

# Part1 - Data Preprocessing

# Import the dataset

In [86]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [75]:
print(x[0])

[619 'France' 'Female' 42.0 2 0.0 1 1.0 1.0 101348.88]


# Encoding categorical data

## Label Encoding the "Gender" column

In [87]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [88]:
print(x[0])

[619 'France' 0 42.0 2 0.0 1 1.0 1.0 101348.88]


## One Hot Encoding he "Geography" column

In [90]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough"
)
x = np.array(ct.fit_transform(x))

In [91]:
print(x[0])

[1.0 0.0 0.0 0.0 619 0 42.0 2 0.0 1 1.0 1.0 101348.88]


## Splitting the dataset into the Training and Test set

In [58]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

## Feature Scaling

In [59]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Part2 - Building the ANN

## Initializing the ANN

In [60]:
ann = tf.keras.models.Sequential()

## Adding the input layer and the first Hidden layer

In [61]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

## Adding the second Hidden layer

In [62]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

## Adding the output layer

In [63]:
# اگر دسته بندی جواب و دسته ها اعداد باینری نباشند در این قسمت متد اکتیویژن مقدار softmax میگیرد(classification)

In [64]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Part3 - Training the ANN

## Compiling the ANN

In [65]:
 # اگر دسته بندی جواب و دسته ها اعداد باینری نباشند در این قسمت متد لاس مقدار categorical_crossentropy میگیرد(classification)

In [66]:
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

## Training the ANN on the Training set

In [67]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7087 - loss: nan
Epoch 2/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7937 - loss: nan
Epoch 3/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7937 - loss: nan
Epoch 4/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7937 - loss: nan
Epoch 5/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7937 - loss: nan
Epoch 6/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7937 - loss: nan
Epoch 7/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7937 - loss: nan
Epoch 8/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7937 - loss: nan
Epoch 9/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7937 - loss: nan
Epoch 10/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7937 - loss: nan
Epoch 11/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7937 - loss: nan
Epoch 12/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7937 -

## Part4 - Making the predictions and evaluating the model

## Predecting the result of a single obsevation

In [72]:
print(x[0])

[1.0 0.0 0.0 0.0 619 0 42.0 2 0.0 1 1.0 1.0 101348.88]


In [92]:
print(
    ann.predict(sc.transform([[1, 0, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
    > 0.5
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
[[False]]


## Predicting the Test set results

In [93]:
y_pred = ann.predict(x_test)
y_pred = y_pred > 0.5
print(
    np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)
)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 1]]


## Making the Confusion Matrix

In [94]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc*100)


[[1614    0]
 [ 387    0]]
80.65967016491754
